/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as smartwalletSol from "./Smartwallet.sol";
export type { smartwalletSol };
export type { Paymaster } from "./Paymaster";
export type { PaymasterToken } from "./PaymasterToken";
export type { Scoin } from "./Scoin";
